// Static atlas images per province (CPRO → files in public/atlas/provinces/).
export const PROVINCE_ATLAS = {
  "01": { name: "Araba / Álava", c: "p003_Provincia_01_Araba_Alava_continuo.png", q: "p004_Provincia_01_Araba_Alava_discreto.png" },
  "02": { name: "Albacete", c: "p005_Provincia_02_Albacete_continuo.png", q: "p006_Provincia_02_Albacete_discreto.png" },
  "03": { name: "Alicante", c: "p007_Provincia_03_Alicante_continuo.png", q: "p008_Provincia_03_Alicante_discreto.png" },
  "04": { name: "Almería", c: "p009_Provincia_04_Almeria_continuo.png", q: "p010_Provincia_04_Almeria_discreto.png" },
  "05": { name: "Ávila", c: "p011_Provincia_05_Avila_continuo.png", q: "p012_Provincia_05_Avila_discreto.png" },
  "06": { name: "Badajoz", c: "p013_Provincia_06_Badajoz_continuo.png", q: "p014_Provincia_06_Badajoz_discreto.png" },
  "07": { name: "Illes Balears", c: "p015_Provincia_07_Balears_Illes_continuo.png", q: "p016_Provincia_07_Balears_Illes_discreto.png" },
  "08": { name: "Barcelona", c: "p017_Provincia_08_Barcelona_continuo.png", q: "p018_Provincia_08_Barcelona_discreto.png" },
  "09": { name: "Burgos", c: "p019_Provincia_09_Burgos_continuo.png", q: "p020_Provincia_09_Burgos_discreto.png" },
  "10": { name: "Cáceres", c: "p021_Provincia_10_Caceres_continuo.png", q: "p022_Provincia_10_Caceres_discreto.png" },
  "11": { name: "Cádiz", c: "p023_Provincia_11_Cadiz_continuo.png", q: "p024_Provincia_11_Cadiz_discreto.png" },
  "12": { name: "Castellón", c: "p025_Provincia_12_Castellon_Castello_continuo.png", q: "p026_Provincia_12_Castellon_Castello_discreto.png" },
  "13": { name: "Ciudad Real", c: "p027_Provincia_13_Ciudad_Real_continuo.png", q: "p028_Provincia_13_Ciudad_Real_discreto.png" },
  "14": { name: "Córdoba", c: "p029_Provincia_14_Cordoba_continuo.png", q: "p030_Provincia_14_Cordoba_discreto.png" },
  "15": { name: "A Coruña", c: "p031_Provincia_15_Coruna_A_continuo.png", q: "p032_Provincia_15_Coruna_A_discreto.png" },
  "16": { name: "Cuenca", c: "p033_Provincia_16_Cuenca_continuo.png", q: "p034_Provincia_16_Cuenca_discreto.png" },
  "17": { name: "Girona", c: "p035_Provincia_17_Girona_continuo.png", q: "p036_Provincia_17_Girona_discreto.png" },
  "18": { name: "Granada", c: "p037_Provincia_18_Granada_continuo.png", q: "p038_Provincia_18_Granada_discreto.png" },
  "19": { name: "Guadalajara", c: "p039_Provincia_19_Guadalajara_continuo.png", q: "p040_Provincia_19_Guadalajara_discreto.png" },
  "20": { name: "Gipuzkoa", c: "p041_Provincia_20_Gipuzkoa_continuo.png", q: "p042_Provincia_20_Gipuzkoa_discreto.png" },
  "21": { name: "Huelva", c: "p043_Provincia_21_Huelva_continuo.png", q: "p044_Provincia_21_Huelva_discreto.png" },
  "22": { name: "Huesca", c: "p045_Provincia_22_Huesca_continuo.png", q: "p046_Provincia_22_Huesca_discreto.png" },
  "23": { name: "Jaén", c: "p047_Provincia_23_Jaen_continuo.png", q: "p048_Provincia_23_Jaen_discreto.png" },
  "24": { name: "León", c: "p049_Provincia_24_Leon_continuo.png", q: "p050_Provincia_24_Leon_discreto.png" },
  "25": { name: "Lleida", c: "p051_Provincia_25_Lleida_continuo.png", q: "p052_Provincia_25_Lleida_discreto.png" },
  "26": { name: "La Rioja", c: "p053_Provincia_26_Rioja_La_continuo.png", q: "p054_Provincia_26_Rioja_La_discreto.png" },
  "27": { name: "Lugo", c: "p055_Provincia_27_Lugo_continuo.png", q: "p056_Provincia_27_Lugo_discreto.png" },
  "28": { name: "Madrid", c: "p057_Provincia_28_Madrid_continuo.png", q: "p058_Provincia_28_Madrid_discreto.png" },
  "29": { name: "Málaga", c: "p059_Provincia_29_Malaga_continuo.png", q: "p060_Provincia_29_Malaga_discreto.png" },
  "30": { name: "Murcia", c: "p061_Provincia_30_Murcia_continuo.png", q: "p062_Provincia_30_Murcia_discreto.png" },
  "31": { name: "Navarra", c: "p063_Provincia_31_Navarra_continuo.png", q: "p064_Provincia_31_Navarra_discreto.png" },
  "32": { name: "Ourense", c: "p065_Provincia_32_Ourense_continuo.png", q: "p066_Provincia_32_Ourense_discreto.png" },
  "33": { name: "Asturias", c: "p067_Provincia_33_Asturias_continuo.png", q: "p068_Provincia_33_Asturias_discreto.png" },
  "34": { name: "Palencia", c: "p069_Provincia_34_Palencia_continuo.png", q: "p070_Provincia_34_Palencia_discreto.png" },
  "35": { name: "Las Palmas", c: "p071_Provincia_35_Palmas_Las_continuo.png", q: "p072_Provincia_35_Palmas_Las_discreto.png" },
  "36": { name: "Pontevedra", c: "p073_Provincia_36_Pontevedra_continuo.png", q: "p074_Provincia_36_Pontevedra_discreto.png" },
  "37": { name: "Salamanca", c: "p075_Provincia_37_Salamanca_continuo.png", q: "p076_Provincia_37_Salamanca_discreto.png" },
  "38": { name: "S.C. de Tenerife", c: "p077_Provincia_38_Santa_Cruz_de_Tenerife_continuo.png", q: "p078_Provincia_38_Santa_Cruz_de_Tenerife_discreto.png" },
  "39": { name: "Cantabria", c: "p079_Provincia_39_Cantabria_continuo.png", q: "p080_Provincia_39_Cantabria_discreto.png" },
  "40": { name: "Segovia", c: "p081_Provincia_40_Segovia_continuo.png", q: "p082_Provincia_40_Segovia_discreto.png" },
  "41": { name: "Sevilla", c: "p083_Provincia_41_Sevilla_continuo.png", q: "p084_Provincia_41_Sevilla_discreto.png" },
  "42": { name: "Soria", c: "p085_Provincia_42_Soria_continuo.png", q: "p086_Provincia_42_Soria_discreto.png" },
  "43": { name: "Tarragona", c: "p087_Provincia_43_Tarragona_continuo.png", q: "p088_Provincia_43_Tarragona_discreto.png" },
  "44": { name: "Teruel", c: "p089_Provincia_44_Teruel_continuo.png", q: "p090_Provincia_44_Teruel_discreto.png" },
  "45": { name: "Toledo", c: "p091_Provincia_45_Toledo_continuo.png", q: "p092_Provincia_45_Toledo_discreto.png" },
  "46": { name: "Valencia", c: "p093_Provincia_46_Valencia_Valencia_continuo.png", q: "p094_Provincia_46_Valencia_Valencia_discreto.png" },
  "47": { name: "Valladolid", c: "p095_Provincia_47_Valladolid_continuo.png", q: "p096_Provincia_47_Valladolid_discreto.png" },
  "48": { name: "Bizkaia", c: "p097_Provincia_48_Bizkaia_continuo.png", q: "p098_Provincia_48_Bizkaia_discreto.png" },
  "49": { name: "Zamora", c: "p099_Provincia_49_Zamora_continuo.png", q: "p100_Provincia_49_Zamora_discreto.png" },
  "50": { name: "Zaragoza", c: "p101_Provincia_50_Zaragoza_continuo.png", q: "p102_Provincia_50_Zaragoza_discreto.png" },
  "51": { name: "Ceuta", c: "p103_Provincia_51_Ceuta_continuo.png", q: "p104_Provincia_51_Ceuta_discreto.png" },
  "52": { name: "Melilla", c: "p105_Provincia_52_Melilla_continuo.png", q: "p106_Provincia_52_Melilla_discreto.png" },
};
